# Unit title

## Overview {-}
Welcome to [insert Course name & #]!  
In this first unit, we begin the course by…  


```{block, type='feedback'}
**Tips for Instructors:**
Here is where we want to hook our students! Set the stage for the main ideas in the unit, questions that may arise, and how topics apply to practice. The Overview can help focus learners on where the unit is heading and motivate them to engage in the unit.
```

##  Topics{-}  
1. *Topic*  
1. *Topic*  
1. *Topic*  
1. *Topic*  


##  Learning Outcomes{-}  
- *Describe…*
- *Contrast…*
- *Analyze…*
- *Determine…*
- *Create…*


##  Activity Checklist{-}  
Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.
```{block, type='reflect'}
#### Unit 1 Learning Activities  

*Activity 1.1:* 📗 Read...    (⏱️ 20 minutes)  
*Activity 1.2:* 🎦 Watch the video...    (⏱️ 8 minutes)  
*Activity 1.3:* 🔍Explore the online resources...    (⏱️ 10 minutes)  
*Activity 1.4:* 💼 Read the Case Study...    (⏱️ 10 minutes)   
*Activity 1.5:* ✏️ Take the ungraded quiz...    (⏱️ 10 minutes)   
```

```{block, type='assessment'}
#### Unit 1 Assessments:  

💬 *Unit 1 Discussion Post*: Respond to the questions posted.  
✏️ *Unit 1 Quiz (5%)*: Assesses your understanding of Unit 1 learning outcomes. Refer to Chapter 1 of your textbook and other online resources.
```

```{block, type='feedback'}
**Tips for Instructors:**
Learning activities are typically ungraded, and can be optional for students, however they are designed to help students learn the material and prepare for the assignments.
```


## Topic Title {-}
[Add content]

```{block, type='feedback'}
**Tips for Instructors:** Topic content can be 1-2 paragraphs or several pages. Consider using instructional videos, graphics, charts, or other images to convey information and appeal to visual learners.
```

### Activity: Introductory Readings & Video {-}
```{block, type='reflect'}

📗 Read ...

#### Questions to Consider{-}  
After completing the activities above, consider the following questions:

- ...  
- ...  

```

*Note that the learning activities in this course are ungraded, unless specified.  They are designed to help you succeed in your assessments in this course, so you are strongly encouraged to complete them.*

```{block, type='feedback'}
**Tips for Instructors:**
As you add the details of the chapter/article/website to read, be sure to add the context for the reading (details about author and/or subject) and relate the reading to the unit learning outcomes.

The "Questions to Consider" feature gives students an opportunity to reflect on readings and make connections, encouraging higher order thinking. In addition to questions, ask students to create graphic organizers and jot down notes in a Reflective Journal.
```


## Topic 2 Title {-}
[add content]


### Activity: Video {-}

```{block, type='reflect'}

🎦 Watch the video...
```


#### Questions to Consider{-}  
After completing the activities above, consider the following questions:

- ...  
- ...  


## Topic 3 Title {-}
[add content]


### Activity: Video {-}

```{block, type='reflect'}

🎦 Watch the video...
```


#### Questions to Consider{-}  
After completing the activities above, consider the following questions:

- ...  
- ...  


## Unit 1 Summary{-}
[add content]


```{block, type='feedback'}
**Tips for Instructors:**
Remind students of a few key points and how they apply to a greater context.  You can mention the assignment or perhaps prepare them for what is in the next unit.
```

##  Assessment{-}
```{block, type='assessment'}
### Assessment Title {-}
See the Assessment section for the Grading Criteria that explains how your discussion contributions will be evaluated.
```

```{block, type='feedback'}
**Tips for Instructors:**
Use a variety of assessment techniques to gauge students understanding of the course learning outcomes. Assessment types include: essays (include drafts/outlines), quizzes, presentations, group projects, discussions, journals, blogs, e-portfolios, interviews, and media projects (infographics, graphic organizer, video, podcast).
```


##  Checking your Learning{-}

```{block, type='progress'}
Now that you have completed the learning activities and assignments for this unit, check the unit learning outcomes below to see if you are able to do the following:

- *Describe…*  
- *Contrast…*  
- *Analyze…*  
- *Determine…*  
- *Create…*  

Feel free to review topics more in depth or continue on to the next unit.
```
