# Sample Unit Format {-}

## Overview {-}

In this first unit, we begin the course by…  




##  Topics {-}  

1. *Topic*  
1. *Topic*  
1. *Topic*  
1. *Topic*  


##  Learning Outcomes{-}  

- *Describe…*
- *Contrast…*
- *Analyze…*
- *Determine…*
- *Create…*


##  Activity Checklist{-}  

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

```{block2, type='reflect'}

<span class="blockhead">Unit 1 Learning Activities </span>

-   
-   

```

```{block2, type='assessment'}
<span class="blockhead">Unit 1 Assessment</span> 

Please check Moodle for details on what you are required to present for this unit.

```

```{block2, type='feedback'}
**Tips for Instructors:**
Learning activities are typically ungraded, and can be optional for students, however they are designed to help students learn the material and prepare for the assignments.
```

## Resources {-}

Here are the resources you will need to complete this unit.

-   
-   

## Topic 1 Title 

[Add content]

```{block2, type='feedback'}
**Tips for Instructors:** Topic content can be 1-2 paragraphs or several pages. Consider using instructional videos, graphics, charts, or other images to convey information and appeal to visual learners.
```

### Activity: Introductory Readings & Video {-}

```{block2, type='reflect'}

📗 Read ...

#### Questions to Consider{-}  
After completing the activities above, consider the following questions:

- ...  
- ...  

```

*Note that the learning activities in this course are ungraded, unless specified.  They are designed to help you succeed in your assessments in this course, so you are strongly encouraged to complete them.*

```{block2, type='feedback'}
**Tips for Instructors:**
As you add the details of the chapter/article/website to read, be sure to add the context for the reading (details about author and/or subject) and relate the reading to the unit learning outcomes.

The "Questions to Consider" feature gives students an opportunity to reflect on readings and make connections, encouraging higher order thinking. In addition to questions, ask students to create graphic organizers and jot down notes in a Reflective Journal.
```


### Learning Activities {-}

### Questions to Consider {-}

## Topic 2 Title 

[add content]




### Questions to Consider{-}  

After completing the activities above, consider the following questions:

- ...  
- ...  


## Topic 3 Title 

[add content]


### Learning Activity {-}

```{block2, type='reflect'}

does this need content
```


#### Questions to Consider{-}  

After completing the activities above, consider the following questions:

- ...  
- ...  


## Unit 1 Summary{-}

[add content]


```{block2, type='feedback'}
**Tips for Instructors:**
Remind students of a few key points and how they apply to a greater context.  You can mention the assignment or perhaps prepare them for what is in the next unit.
```

##  Assessment{-}

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

Please check Moodle for details on what you are required to present for this unit.

```

```{block2, type='feedback'}
**Tips for Instructors:**
Use a variety of assessment techniques to gauge students understanding of the course learning outcomes. Assessment types include: essays (include drafts/outlines), quizzes, presentations, group projects, discussions, journals, blogs, e-portfolios, interviews, and media projects (infographics, graphic organizer, video, podcast).
```


##  Checking your Learning{-}

```{block2, type='progress'}
Now that you have completed the learning activities and assignments for this unit, check the unit learning outcomes below to see if you are able to do the following:

- *Describe…*  
- *Contrast…*  
- *Analyze…*  
- *Determine…*  
- *Create…*  

Feel free to review topics more in depth or continue on to the next unit.
```
